FROM tutum/apache-php:latest

RUN apt-get update
RUN apt-get install git -y
RUN apt-get update
RUN apt-get install wget -y
RUN apt-get install unzip -y
RUN apt-get install vim -y
RUN rm -fr /app
ADD . /app
ADD . /stuff
WORKDIR /stuff
RUN wget https://codeload.github.com/opencart/opencart/zip/master
RUN unzip master
WORKDIR /
RUN echo "COPYING:"
RUN ls -al /stuff
RUN cp -a stuff/opencart-master/upload/. app
RUN mv app/config-dist.php app/config.php
RUN mv app/admin/config-dist.php app/admin/config.php
WORKDIR /app
RUN chmod 0777 system/storage/cache/
RUN chmod 0777 system/storage/download/
RUN chmod 0777 system/storage/logs/
RUN chmod 0777 system/storage/modification/
RUN chmod 0777 system/storage/session/
RUN chmod 0777 system/storage/upload/
RUN chmod 0777 system/storage/vendor/
RUN chmod 0777 image/
RUN chmod 0777 image/cache/
RUN chmod 0777 image/catalog/
RUN chmod 0777 config.php
RUN chmod 0777 admin/config.php

EXPOSE 80
